version: '3'

services:
    db_mongo:
        build: ./mongodb

    web_app:
        build: ./nodejs_sample_app
        ports:
          - 3000:3000
        environment:
          - DB_HOST=mongodb://db_mongo:27017/posts
        depends_on:
          - db_mongo

